name: Navigator
version: 1.0
author: Saith
main: de.mcharvest.saith.NavigatorPlugin
commands:
  destination:
permissions:
  navigator.destination.set:
    default: op
  navigator.destination.add:
    default: op
  navigator.destination.find:
    default: op
  navigator.destination.create:
    default: op
  navigator.destination.remove:
    default: op
  navigator.destination.ride:
    default: op
  navigator.*:
    default: op
    children:
      navigator.destination.set: true
      navigator.destination.add: true
      navigator.destination.find: true
      navigator.destination.remove: true
      navigator.destination.ride: true
      navigator.destination.create: true