name: Navigator
version: 1.0
author: Saith
main: de.mcharvest.saith.Main
commands:
  destination:
permissions:
  navigator.destination.set:
    default: op
  navigator.destination.add:
    default: op
  navigator.destination.find:
    default: op
  navigator.*:
    default: op
    children:
      navigator.destination.set: true
      navigator.destination.add: true
      navigator.destination.find: true